version: '3.1'

services:
  db:
    container_name: postgres-auth
    image: postgres
    restart: always
    ports:
      - 5442:5432
    env_file:
      - docker.env
    volumes:
      - ./docker_entrypoint/init.sql:/docker-entrypoint-initdb.d/init.sql
      - auth_db:/var/lib/postgresql/data
    networks:
      - auth_db_net

  adminer:
    image: adminer
    restart: always
    ports:
      - 9456:8080
    networks:
      - auth_db_net

  chroma-server:
    image: chroma-server-image:latest
    volumes:
      - chroma_data:/chroma
      - index_data:/index_data
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config log_config.yml
    environment:
      - CHROMA_DB_IMPL=clickhouse
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
    ports:
      - 8000:8000
    depends_on:
      - chroma-clickhouse
    networks:
      - chroma_net

  clickhouse:
    image: clickhouse/clickhouse-server:22.9-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_TCP_PORT=9000
      - CLICKHOUSE_HTTP_PORT=8123
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
      - backups:/backups
      - clickhouse_config:/etc/clickhouse-server/config.d/backup_disk.xml
      - clickhouse_config:/etc/clickhouse-server/users.d/chroma.xml
    networks:
      - chroma_net

  gen_app:
    container_name: generative-app
    image: generative-app
    restart: unless-stopped
    ports:
      - 8504:8504
    volumes:
      - ./.streamlit/docker_secrets.toml:/app/.streamlit/secrets.toml
      - sandboxes:/app/generative_app/sandboxes
    networks:
      - auth_db_net
      - chroma_net

networks:
  auth_db_net:
    driver: bridge
  chroma_net:
    driver: bridge

volumes:
  sandboxes:
  auth_db:
  chroma_data:
  clickhouse_data:
    driver: local
  clickhouse_logs:
    driver: local
  clickhouse_config:
    driver: local
  index_data:
    driver: local
  backups:
    driver: local