import streamlit as st
import pandas as pd

def dynamic(uploaded_file: pd.DataFrame):
    """
    this function will be replaced by the code generated by the LLM after the prompt of the user
    uploaded_file: is a panda dataframe pd.DataFrame
    """
    st.write("This content will be replaced")