openai_api_key = "your key here"
tries = 15

[server]
runOnSave = true

[postgres]
host = "localhost"
port = 5432
dbname = "xxx"
user = "xxx"
password = "xxx"

[chroma]
host = "localhost"
port = "8000"

[langchain]
debug = false